version: '3.7'

services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8010"
    ports:
      - 8010:8888
    volumes:
      - ./pfaunk/:/code/pfaunk
    env_file: .env
    working_dir: /code/pfaunk/
    command: /root/.cache/pypoetry/virtualenvs/pfaunk-MATOk_fk-py3.7/bin/jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
