version: '3.7'

services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8020"
    ports:
      - 8020:8888
    volumes:
      - ./pfunk/:/code/pfunk
    env_file: .env
    working_dir: /code/
    command: /root/.cache/pypoetry/virtualenvs/pfunk-MATOk_fk-py3.7/bin/jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
